version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_histo_car
    restart: always
    environment:
      POSTGRES_USER: histo_car_user
      POSTGRES_PASSWORD: histo_car_password
      POSTGRES_DB: histo_car_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis_histo_car
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    build: .
    container_name: histo_car_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: histo_car_user
      DATABASE_PASSWORD: histo_car_password
      DATABASE_NAME: histo_car_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    command: sh ./src/scripts/start.sh
    volumes:
      - ./src:/app/src
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
